# Generated by Django 4.2.5 on 2023-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokedexDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=30)),
                ('pokemon_level', models.IntegerField()),
                ('pokemon_height', models.IntegerField()),
                ('pokemon_move', models.CharField(max_length=30)),
                ('pokemon_image', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
