# Generated by Django 4.2.5 on 2023-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_alter_pokedexdatabase_pokemon_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_level',
            field=models.IntegerField(null=True),
        ),
    ]
