# Generated by Django 4.2.5 on 2023-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_alter_pokedexdatabase_pokemon_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_image',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_move',
            field=models.JSONField(default=list, null=True),
        ),
    ]
