# Generated by Django 4.2.5 on 2023-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_alter_pokedexdatabase_pokemon_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
