# Generated by Django 4.2.5 on 2023-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0005_alter_pokedexdatabase_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_image',
            field=models.URLField(null=True),
        ),
    ]
