# Generated by Django 4.2.5 on 2023-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0006_alter_pokedexdatabase_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexdatabase',
            name='pokemon_level',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
